<a href="https://colab.research.google.com/github/Aman-Gautam1/NLP-basics/blob/main/word_embeddings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words here',
     'i am a good person']

In [ ]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words here',
 'i am a good person']

In [ ]:
 ### Vocabulary size
voc_size=500

In [ ]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[352, 11, 260, 337], [352, 11, 260, 450], [352, 8, 260, 479], [131, 24, 306, 406, 294], [131, 24, 306, 406, 421], [241, 352, 83, 260, 438, 241], [131, 24, 306, 406, 11]]


In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [ ]:
import numpy as np

In [ ]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 352  11 260 337]
 [  0   0   0   0 352  11 260 450]
 [  0   0   0   0 352   8 260 479]
 [  0   0   0 131  24 306 406 294]
 [  0   0   0 131  24 306 406 421]
 [  0   0 241 352  83 260 438 241]
 [  0   0   0 131  24 306 406  11]]


In [ ]:
dim=10


In [ ]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [ ]:
embedded_docs[0]

array([  0,   0,   0,   0, 352,  11, 260, 337], dtype=int32)

In [ ]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 131ms/step


array([[ 0.02220995, -0.01676138,  0.02520332, -0.03219835, -0.00706277,
         0.01547896, -0.02638284,  0.02024159,  0.01761365, -0.04712958],
       [ 0.02220995, -0.01676138,  0.02520332, -0.03219835, -0.00706277,
         0.01547896, -0.02638284,  0.02024159,  0.01761365, -0.04712958],
       [ 0.02220995, -0.01676138,  0.02520332, -0.03219835, -0.00706277,
         0.01547896, -0.02638284,  0.02024159,  0.01761365, -0.04712958],
       [ 0.02220995, -0.01676138,  0.02520332, -0.03219835, -0.00706277,
         0.01547896, -0.02638284,  0.02024159,  0.01761365, -0.04712958],
       [-0.01412677, -0.00133123,  0.04605118, -0.01500261,  0.03699309,
        -0.04017075, -0.02321335,  0.02488441,  0.0078465 , -0.0391016 ],
       [ 0.00212055,  0.02418577,  0.02440417, -0.04807011, -0.00911683,
         0.01226604, -0.01289967, -0.0426742 ,  0.03079034, -0.02686424],
       [-0.01070353, -0.03830882, -0.041308  , -0.0114005 ,  0.00128608,
        -0.03516011,  0.02768669, -0.01522727

In [ ]:
 print(model.predict(embedded_docs))

1/1 [==============================] - 0s 45ms/step
[[[ 0.02220995 -0.01676138  0.02520332 -0.03219835 -0.00706277
    0.01547896 -0.02638284  0.02024159  0.01761365 -0.04712958]
  [ 0.02220995 -0.01676138  0.02520332 -0.03219835 -0.00706277
    0.01547896 -0.02638284  0.02024159  0.01761365 -0.04712958]
  [ 0.02220995 -0.01676138  0.02520332 -0.03219835 -0.00706277
    0.01547896 -0.02638284  0.02024159  0.01761365 -0.04712958]
  [ 0.02220995 -0.01676138  0.02520332 -0.03219835 -0.00706277
    0.01547896 -0.02638284  0.02024159  0.01761365 -0.04712958]
  [-0.01412677 -0.00133123  0.04605118 -0.01500261  0.03699309
   -0.04017075 -0.02321335  0.02488441  0.0078465  -0.0391016 ]
  [ 0.00212055  0.02418577  0.02440417 -0.04807011 -0.00911683
    0.01226604 -0.01289967 -0.0426742   0.03079034 -0.02686424]
  [-0.01070353 -0.03830882 -0.041308   -0.0114005   0.00128608
   -0.03516011  0.02768669 -0.01522727  0.01651852 -0.04704219]
  [-0.03069253 -0.037806    0.04847476  0.0235309   0.03345

In [ ]:
embedded_docs[0]

array([  0,   0,   0,   0, 352,  11, 260, 337], dtype=int32)

In [ ]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 20ms/step


array([[ 0.02220995, -0.01676138,  0.02520332, -0.03219835, -0.00706277,
         0.01547896, -0.02638284,  0.02024159,  0.01761365, -0.04712958],
       [ 0.02220995, -0.01676138,  0.02520332, -0.03219835, -0.00706277,
         0.01547896, -0.02638284,  0.02024159,  0.01761365, -0.04712958],
       [ 0.02220995, -0.01676138,  0.02520332, -0.03219835, -0.00706277,
         0.01547896, -0.02638284,  0.02024159,  0.01761365, -0.04712958],
       [ 0.02220995, -0.01676138,  0.02520332, -0.03219835, -0.00706277,
         0.01547896, -0.02638284,  0.02024159,  0.01761365, -0.04712958],
       [-0.01412677, -0.00133123,  0.04605118, -0.01500261,  0.03699309,
        -0.04017075, -0.02321335,  0.02488441,  0.0078465 , -0.0391016 ],
       [ 0.00212055,  0.02418577,  0.02440417, -0.04807011, -0.00911683,
         0.01226604, -0.01289967, -0.0426742 ,  0.03079034, -0.02686424],
       [-0.01070353, -0.03830882, -0.041308  , -0.0114005 ,  0.00128608,
        -0.03516011,  0.02768669, -0.01522727